# TCL File Generated by Component Editor 16.1
# Mon Dec 17 21:47:37 GMT+08:00 2018
# DO NOT MODIFY


# 
# Packet_Symbol_Width_adapter "Packet Symbol Width Adapter" v1.0
# CNLHC 2018.12.17.21:47:37
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module Packet_Symbol_Width_adapter
# 
set_module_property DESCRIPTION ""
set_module_property NAME Packet_Symbol_Width_adapter_tx
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP DigiC/Utility
set_module_property AUTHOR CNLHC
set_module_property DISPLAY_NAME "Packet Symbol Width Adapter TX"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 

# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_reset reset Input 1


# 
# connection point aso_out0
# 
add_interface aso_out0 avalon_streaming start
set_interface_property aso_out0 associatedClock clock
set_interface_property aso_out0 associatedReset reset
set_interface_property aso_out0 dataBitsPerSymbol 8
set_interface_property aso_out0 errorDescriptor ""
set_interface_property aso_out0 firstSymbolInHighOrderBits true
set_interface_property aso_out0 maxChannel 0
set_interface_property aso_out0 readyLatency 0
set_interface_property aso_out0 ENABLED true
set_interface_property aso_out0 EXPORT_OF ""
set_interface_property aso_out0 PORT_NAME_MAP ""
set_interface_property aso_out0 CMSIS_SVD_VARIABLES ""
set_interface_property aso_out0 SVD_ADDRESS_GROUP ""

add_interface_port aso_out0 aso_out0_data data Output 32
add_interface_port aso_out0 aso_out0_ready ready Input 1
add_interface_port aso_out0 aso_out0_valid valid Output 1
add_interface_port aso_out0 aso_out0_endofpacket endofpacket Output 1
add_interface_port aso_out0 aso_out0_startofpacket startofpacket Output 1


# 
# connection point asi_in0
# 
add_interface asi_in0 avalon_streaming end
set_interface_property asi_in0 associatedClock clock
set_interface_property asi_in0 associatedReset reset
set_interface_property asi_in0 dataBitsPerSymbol 8
set_interface_property asi_in0 errorDescriptor ""
set_interface_property asi_in0 firstSymbolInHighOrderBits true
set_interface_property asi_in0 maxChannel 0
set_interface_property asi_in0 readyLatency 0
set_interface_property asi_in0 ENABLED true
set_interface_property asi_in0 EXPORT_OF ""
set_interface_property asi_in0 PORT_NAME_MAP ""
set_interface_property asi_in0 CMSIS_SVD_VARIABLES ""
set_interface_property asi_in0 SVD_ADDRESS_GROUP ""

add_interface_port asi_in0 asi_in0_data data Input 32
add_interface_port asi_in0 asi_in0_ready ready Output 1
add_interface_port asi_in0 asi_in0_valid valid Input 1
add_interface_port asi_in0 asi_in0_endofpacket endofpacket Input 1
add_interface_port asi_in0 asi_in0_startofpacket startofpacket Input 1

# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH generate ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL Packet_Symbol_Width_adapter_TX
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
#add_fileset_file Packet_Symbol_Width_adapter.v VERILOG PATH Packet_Symbol_Width_adapter.v TOP_LEVEL_FILE

add_parameter INPUT_SYMBOL_WIDTH INTEGER 32 ""
set_parameter_property INPUT_SYMBOL_WIDTH DEFAULT_VALUE 32
set_parameter_property INPUT_SYMBOL_WIDTH DISPLAY_NAME INPUT_SYMBOL_WIDTH
set_parameter_property INPUT_SYMBOL_WIDTH TYPE INTEGER
set_parameter_property INPUT_SYMBOL_WIDTH UNITS None
set_parameter_property INPUT_SYMBOL_WIDTH ALLOWED_RANGES 1:256
set_parameter_property INPUT_SYMBOL_WIDTH DESCRIPTION ""
add_parameter OUTPUT_SYMBOL_WIDTH INTEGER 16 ""
set_parameter_property OUTPUT_SYMBOL_WIDTH DEFAULT_VALUE 16
set_parameter_property OUTPUT_SYMBOL_WIDTH DISPLAY_NAME OUTPUT_SYMBOL_WIDTH
set_parameter_property OUTPUT_SYMBOL_WIDTH TYPE INTEGER
set_parameter_property OUTPUT_SYMBOL_WIDTH UNITS None
set_parameter_property OUTPUT_SYMBOL_WIDTH ALLOWED_RANGES 1:256
set_parameter_property OUTPUT_SYMBOL_WIDTH DESCRIPTION ""


set_module_property ELABORATION_CALLBACK elaborate

proc elaborate {} {
	set tIW [expr [get_parameter_value INPUT_SYMBOL_WIDTH] ]
	set tOW [expr [get_parameter_value OUTPUT_SYMBOL_WIDTH] ]
    set_interface_property asi_in0 dataBitsPerSymbol $tIW
    set_interface_property aso_out0 dataBitsPerSymbol $tOW
    set_port_property asi_in0_data WIDTH_EXPR   "$tIW"
    set_port_property aso_out0_data WIDTH_EXPR  "$tOW"
}
proc generate {entity_name} {
	set tIW [expr [get_parameter_value INPUT_SYMBOL_WIDTH] ]
	set tOW [expr [get_parameter_value OUTPUT_SYMBOL_WIDTH] ]
    set fileID [open "./Packet_Symbol_Width_adapter_TX.v" r]
    set temp ""
    while {[eof $fileID] != 1} {
        gets $fileID lineInfo
        regsub -all {parameter INPUT_SYMBOL_WIDTH.*\d+} $lineInfo [format {parameter INPUT_SYMBOL_WIDTH=%d} $tIW] lineInfo
        regsub -all {parameter OUTPUT_SYMBOL_WIDTH.*\d+} $lineInfo  [format {parameter OUTPUT_SYMBOL_WIDTH=%d} $tOW] lineInfo
        append temp "${lineInfo}\n"
    }
    add_fileset_file "Packet_Symbol_Width_adapter_TX.v" VERILOG TEXT $temp
}

